apiVersion: v1
kind: Pod

metadata:
  name: configmap-pod

spec:
  containers:
    - name: nginx
      image: nginx:latest

      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME

        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT