apiVersion: v1
kind: Pod

metadata:
  name: app-pod

spec:
  containers:
    - name: nginx
      image: nginx

      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password